version: '3'
  
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db_progress
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
